unit uPrincipal;


// Esta unit  só conhece o CONTROLE -- veja o "USES" do IMPLEMENTACION


interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls;

type
  TfrmSped = class(TForm)
    btParametros: TButton;
    btGeracao: TButton;
    procedure btParametrosClick(Sender: TObject);
  private

  public

  end;

var
  frmSped: TfrmSped;

implementation

uses
   uControleConfiguracoes;


{$R *.dfm}

procedure TfrmSped.btParametrosClick(Sender: TObject);
var
   lControle: TControle;
begin
   lControle := TControle.Create;
   lControle.Initialize;
end;

end.
/****              Generated by IBExpert 24/11/2014 23:00:37               ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/

CREATE TABLE SPED (
    ID       INTEGER,
    EMPRESA  INTEGER
);




CREATE TABLE I010 (
    ID                  INTEGER,
    SPED                INTEGER,
    INDICADOROPERACOES  INTEGER
);


CREATE GENERATOR SPED;
CREATE GENERATOR I010;

